sudo: required

language: node_js

node_js: 6.9.5

services:
  - docker

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost
    - kubernetes.default

before_script:
  - npm install -g grunt-cli
  - docker pull alpine:latest
  - sudo apt-get update && sudo apt-get install -y apt-transport-https curl
  - echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee --append /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update && sudo apt-get install -y kubelet kubeadm kubectl kubernetes-cni
  - curl -o flannel.yml https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  - kubeadm init --pod-network-cidr 10.244.0.0/16
  - kubectl taint nodes --all dedicated-
  - kubectl apply -f flannel.yml

script:
  - grunt coverage
