sudo: required

language: node_js

node_js: 6.9.5

services:
  - docker

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost
    - kubernetes.default

before_script:
  - npm install -g grunt-cli
  - docker pull alpine:latest

script:
  - grunt coverage
