sudo: required

language: node_js

node_js: 6.9.5

services:
  - docker

branches:
  only:
    - staging
    - master

addons:
  hosts:
    - localhost
    - dev-controller
    - kubernetes.default

before_script:
  - npm install -g grunt-cli
  - docker pull alpine:latest
  - export K8S_VERSION=$(curl -sS https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  - export ARCH=amd64
  - docker run -d --volume=/:/rootfs:ro --volume=/sys:/sys:rw --volume=/var/lib/docker/:/var/lib/docker:rw --volume=/var/lib/kubelet/:/var/lib/kubelet:rw --volume=/var/run:/var/run:rw --net=host --pid=host --privileged gcr.io/google_containers/hyperkube-${ARCH}:${K8S_VERSION} /hyperkube kubelet --containerized --hostname-override=127.0.0.1 --api-servers=http://localhost:8443 --config=/etc/kubernetes/manifests --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --allow-privileged --v=2
  - sudo curl -sSL "http://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/linux/amd64/kubectl" > ./kubectl
  - sudo chmod +x ./kubectl
  - ./kubectl config set-cluster travis --server=http://localhost:8443
  - ./kubectl config set-context travis --cluster=travis
  - ./kubectl config use-context travis
  - while [ $(./kubectl get nodes | grep 127.0.0.1 | grep Ready | wc -l) -eq 0 ]; do sleep 1; done

script:
  - grunt coverage
